M48
; DRILL file {KiCad (6.0.1-0)} date Saturday, June 04, 2022 at 08:14:06 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-04T20:14:06-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.250
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C6.500
%
G90
G05
T2
X150.0Y-74.5
T1
X108.45Y-97.6G85X110.95Y-97.6
G05
X189.05Y-97.6G85X191.55Y-97.6
G05
T0
M30
